on:
  pull_request:
    branches:
    - main

jobs:
  CI_Solidity:
    runs-on: ubuntu-latest
    steps:  
        - name: Install NPM dependencies
          run: npm install

        - name: Install PIP dependencies
          run: python -m pip install -r requirements.txt
          
        - name: Run Solidity Linter
          run: npm run lint
          
        - name: Run Solidity Prettier
          run: npm run prettier
          
        - name: Activate the virtual env
          run: ./.venv/scripts/activate
          
        - name: Compile Contracts
          run: brownie compile
          
        - name: Run tests
          run: brownie test
          
        - name: Run Slither
          run: Slither

  CI_Python:
      runs-on: ubuntu-latest
      steps:
        - name: Run Python Linter
          run: pylint ./**/*.py
          
        - name: Run Python Prettier
          run: black ./**/*.py
